def chorus():
    print()
    print("Down by the bay")
    print("Where the watermelons grow")
    print("Back to my home")
    print("I dare not go")
    print("For if I do")
    print("My mother will say...")
    print()
 
chorus()
print("Did you ever see a baboon, holding a balloon?")
chorus()
print("Did you ever see a whale, with a polka-dot tail?")
chorus()
print("Did you ever see a pig, wearing a wig?")
chorus()
print("Did you ever see a goat, standing in a boat?")
chorus()
print("Did you ever see a llama, wearing pajamas?")